### ISSUE TITLE
how can i create events?

### ISSUE THREAD

**Issue by talalong** [jasonjoh/php-tutorial#11]
This is not really an issue, but could you please show me the way to create and delete events?
thank you.

**Comment by jasonjoh** [comment]
https://msdn.microsoft.com/en-us/office/office365/api/calendar-rest-operations#create-events
https://msdn.microsoft.com/en-us/office/office365/api/calendar-rest-operations#delete-events

Try our [sandbox](https://oauthplay.azurewebsites.net/) if you want to play with the API.
