### ISSUE TITLE
Send Email 403 Error

### ISSUE THREAD

**Issue by imtiazPabel** [jasonjoh/php-tutorial#12]
I can fetch email using Rest api,but when i try to send email using Rest api it show's me Request returned HTTP error 403.I can't understand where is the problem
```
$params = [
            "Message" => [
                "Subject" => "Meet for lunch?",
                "Body" => [
                    "ContentType" => "Text",
                    "Content" => "The new cafeteria is open.",
                ],
                "ToRecipients" => [
                    [
                        "EmailAddress" => [
                            "Address" => "pabel201611@gmail.com"
                        ]
                    ]
                ],

            ],
            "SaveToSentItems" => "false"
        ];

        $params = json_encode($params, true);
        $getMessagesUrl = self::$outlookApiUrl."/me/sendmail";
        return self::makeApiCall($access_token, $user_email, "POST", $getMessagesUrl, $params);
```

**Comment by jasonjoh** [comment]
This sample doesn't send mail, so this isn't really an issue per se. If you're getting a 403, it's helpful to get the body of the response to see what message it returned (if any). You should make sure that you're requesting the `mail.send` scope too.

**Comment by imtiazPabel** [comment]
It's just response on body "HTTP error found 403"  nothing else.If i am trying in wrong way,please give a reference what will be right.

**Comment by jasonjoh** [comment]
Your code looks fine, it's likely a problem with your access token.

**Comment by imtiazPabel** [comment]
access token has no problem,i can fetch my email using same access token,but when try to send email it's gonna problem.

**Comment by jasonjoh** [comment]
That's what I'm saying. You most likely do not have the required scope to send mail, only to read mail. Try pasting your token in http://jwt.calebb.net and look at the `scp` claim.

**Comment by imtiazPabel** [comment]
can you please show me an example how i send request to send email.

**Comment by imtiazPabel** [comment]
Hey @jasonjoh did you get any solution for me?

**Comment by jasonjoh** [comment]
Sorry I've been on vacation for the holidays. Your code looks fine, so I don't have a sample that's different to show you. Did you put your token into that parser? What does it look like?

**Comment by imtiazPabel** [comment]
Yes i put the token in parser.And got the message "HTTP error found 403".You know what using same token i can fetch mail,but can't send mail.

**Comment by jasonjoh** [comment]
You never confirmed to me that you are actually requesting the `mail.send` scope that I mentioned on Dec. 7, and you haven't told me what's in the `scp` claim of your token after putting it through the parser. I am assuming that you're using the sample as-is, and if so, then it is expected you will get a 403 if you try to send mail. The sample doesn't request permission to do so.
