### ISSUE TITLE
How do I attach files which are located on my web server to send email?

### ISSUE THREAD

**Issue by dipens** [jasonjoh/php-tutorial#13]
Hello,

I am trying to send email following the docs on https://msdn.microsoft.com/office/office365/APi/mail-rest-operations#SendMessageOnTheFly with PHP. So far I can send a plain email with no attachments.  But how do I do it with attachments?

According to docs this is what the response should look like:

```
POST https://outlook.office.com/api/v2.0/me/sendmail

{
  "Message": {
    "Subject": "Meet for lunch?",
    "Body": {
      "ContentType": "Text",
      "Content": "The new cafeteria is open."
    },
    "ToRecipients": [
      {
        "EmailAddress": {
          "Address": "garthf@a830edad9050849NDA1.onmicrosoft.com"
        }
      }
    ],
    "Attachments": [
      {
        "@odata.type": "#Microsoft.OutlookServices.FileAttachment",
        "Name": "menu.txt",
        "ContentBytes": "bWFjIGFuZCBjaGVlc2UgdG9kYXk="
      }
    ]
  },
  "SaveToSentItems": "false"
}
```

What I have is this:
```
$arr= array(
    "Message" =>array(
        'Subject' => $subject,
        "Body"=>array(
            "ContentType"=>"HTML",
            "Content"=>$Content,
        ),
        "ToRecipients"=>array(
            array(
                "EmailAddress"=>array(
                    "Address"=>$email,
                )
            ),
        ),
        "Attachments"=> array(
            "@odata.type"=> "#Microsoft.OutlookServices.FileAttachment",
            "Name"=> /var/www/html/the/physical/location/of/file,
            "ContentBytes"=> "No idea what I should put here"
        ),
    ));

$json=json_encode($arr, true);
```

I am clueless about going with this. Ofcourse its not working and giving me a 400 error. 

What should I be doing here? What's the right format? 

Any heads up will be much appreciated. Thank you.

**Comment by jasonjoh** [comment]
I see your post on SO: http://stackoverflow.com/questions/41250887/how-do-i-attach-files-which-are-located-on-my-web-server-to-send-email. Closing this issue.

**Comment by dipens** [comment]
Hello Jason. just to make it clear my issue still exists. The answer given on SO just fixes one typo that I had but doesn't fix my existent problem. So please have a look at it when you have some time. Thank you.
