### ISSUE TITLE
Having trouble setting this up on my web hosting

### ISSUE THREAD

**Issue by bobbyarcher** [jasonjoh/php-tutorial#14]
Hi! I am trying to replicate what you have done here, but on a web app I am creating, instead of on IIS 8. The app is currently hosted on a shared server. Could this be the route of my problem?

I have done everything you have done, but have put the redirect url as http://www.appdot.a2hosted.com/php-tutorial/authorize.php (the current domain I am using to build the web app) on the Application Registration portal, and in the authorize.php file.

When I try to log in, it allows me to enter my details, then says 'We're taking you to the Microsoft Account sign in page', but then the following page shows:

<img width="946" alt="screen shot 2017-03-08 at 21 23 40" src="https://cloud.githubusercontent.com/assets/26286809/23724698/98b98f50-0445-11e7-9ccd-f8d088772a83.png">

Any help with this would be very much appreciated!!!

**Comment by jasonjoh** [comment]
Your redirect needs to be https. I'm surprised it let you even register it that way. There should be no problem having it on a hosted server.

**Comment by bobbyarcher** [comment]
Set it up as https and it works perfectly! Thanks a lot!
