### ISSUE TITLE
Undefined Index 'code' on authorize.php line 6

### ISSUE THREAD

**Issue by mlong635** [jasonjoh/php-tutorial#15]
Hi Jason,

I am currently getting an error after signing in on https://login.microsoftonline.com, that leads me back to http://localhost/php-tutorial/authorize.php, "Notice: Undefined index: code in /[pathto]/php-tutorial/authorize.php on line 6".  And therefore getting a "ERROR: Token request returned HTTP error 400".  From what I can tell, I have everything set up correctly with the MS php-tutorial registration, and the $clientId and $clientSecret.

I am using php 7 if that matters.  I am pretty new to php.  Can you please let me know how I can fix this?  Thank you.

**Comment by mlong635** [comment]
The line that is causing the error from authorize.php

$auth_code = $_GET['code'];

**Comment by jasonjoh** [comment]
That would indicate that when Azure redirects back to your app, it is not including a `code` parameter in the URL. Most likely this is due to some error condition. Check the entire URL, there's probably an `error` parameter that will tell you more about what's going on.

**Comment by mlong635** [comment]
Thanks Jason.  URL contained "error_description=AADSTS50001%3a+Resource+%27https%3a%2f%2foutlook.office.com%27+is+disabled".  I don't know how it got disabled but I re-enabled outlook and it is working.  

Thanks again Jason.  Great tutorial.

**Comment by jasonjoh** [comment]
Thanks, glad you found it helpful! I have an update to use Laravel to create the app and to use the Graph SDK rather than hit the Outlook API directly. I'll likely push this in the next week or so.
