### ISSUE TITLE
proxy graph

### ISSUE THREAD

**Issue by eternia** [jasonjoh/php-tutorial#16]
Hi, 

i have an error with curl i have added proxy to: AuthController
'proxy'                   => '195.6.208.115:3128',

It's ok juste i have the same error with the OutlookController because the microsoft graph haven't an proxy option how to add it ?

**Comment by jasonjoh** [comment]
This would be a question better suited for the [Graph SDK repository](https://github.com/microsoftgraph/msgraph-sdk-php). I took a quick look over there, and according to their docs, they use [Guzzle](https://github.com/guzzle/guzzle), so you may be able to configure a proxy according to [their docs](http://docs.guzzlephp.org/en/stable/request-options.html?highlight=proxy#proxy).
