### ISSUE TITLE
How to use the code for a simple "Sign in with Outlook" button on existing site?

### ISSUE THREAD

**Issue by anki-code** [jasonjoh/php-tutorial#17]
Hi! @jasonjoh thank you for great work!

Could you please help me reduce the code (or just write one oauth2callback.php on current code)  to do a button "Login with Outlook" for the main page.

For example, Google OAuth2 has just 1 file for it (oauth2callback.php + github library) — https://developers.google.com/api-client-library/php/auth/web-app#example — I need something simple as it solution.

**Comment by jasonjoh** [comment]
I'm sure you could do this, the relevant code for the callback is in AuthController.php.
