### ISSUE TITLE
Searching specific folders

### ISSUE THREAD

**Issue by LarryBarker** [jasonjoh/php-tutorial#18]
I have a fairly unique situation where I am using aliases for multiple clients (150+) under one main account. I would like to allow my users to login to our site and retrieve only the messages sent to their alias. After reading some of the Graph documentation and experimenting with Graph Explorer, I found the $search= parameter. 

So, I replaced the line:
`$getMessagesUrl = '/me/mailfolders/inbox/messages?'.http_build_query($messageQueryParams);` 
from the tutorial with:
`$getMessagesUrl = '/me/messages?$search="'. $alias .'"';`

However, what I have found is that this obviously searches all messages containing the alias, when I really want just the inbox. 

Currently, we have messages sorted into folders using rules. So I looked into targeting the specific folder but found this was next to impossible as the folderIDs are difficult to retrieve.

Do you have any suggestions for my situation? Thanks for the great tutorial to help me get started.

**Comment by jasonjoh** [comment]
Thanks, I'm glad you found it helpful!

So yes, if you query the `/me/messages` endpoint, you get messages in all folders (except Deleted Items, Junk, and I believe Drafts). So if you want a specific folder, you need to use the `/me/mailfolders/{id}/messages` endpoint.

If you're targeting a default folder like Inbox, then it's easy. You can just use `inbox` as the ID. Other non-default folders are a little trickier, but it's not too difficult. However, you do need to know where to look for the folder, as you'll need to walk the folder tree to get the target folder's ID.

Say for example, that the folder you want is in the path Inbox->SubFolder->TargetFolder. Inbox we get for free, so you could start by querying it's child folders for the "SubFolder" folder:

```
GET /me/mailfolders/inbox/childfolders?$filter=displayName eq 'SubFolder'
```

That would get you back the folder, and you can read the `id` from the response. We then repeat the above query, swapping in the `id` and changing the filter to look for `TargetFolder`:

```
GET /me/mailfolders/{id of SubFolder}/childfolders?$filter=displayName eq 'TargetFolder'
```

Again you read the `id` from the response, then you can plug it into the URL for your search query:

```
$getMessagesUrl = '/me/mailfolders/{id of TargetFolder}/messages?$search="'. $alias .'"';
```

**Comment by LarryBarker** [comment]
Awesome, thank you for the quick response, took me a little bit to get everything straigtened out but I believe I have it. Here's my final solution:
`$getFoldersUrl = "/me/mailfolders/inbox/childfolders?\$filter=contains(displayName,'$folderName')";

        $folder = $graph->createRequest('GET', $getFoldersUrl)
                        ->setReturnType(Model\Folder::class)
                        ->execute();

        $folderId = $folder[0]->getId();

        $getMessagesUrl = "/me/mailfolders/".$folderId."/messages";
        
        $this->messages = $graph->createRequest('GET', $getMessagesUrl)
                        ->addHeaders(array ('X-AnchorMailbox' => $user->getMail()))
                        ->setReturnType(Model\Message::class)
                        ->execute();

        $this->getFoldersUrl = $getFoldersUrl;`

I guess now I am interested in displaying a single message in its entirety.

**Comment by LarryBarker** [comment]
Done and finished #19 as well.

**Comment by LarryBarker** [comment]
Do you have time to help with an issue I’m having with moving my development files over to my production server?
Currently I am getting this error:
No access token has been provided.

I moved everything over without any problems.

You can visit wwrfresource.com/mail to see for yourself.

Thanks.

**Comment by jasonjoh** [comment]
There's really only so much I can do, I'm hardly a PHP expert :). The only thing that comes to mind is to make sure you update your app registration's redirect URI to the production server's URL so the OAuth flow will work correctly.

**Comment by LarryBarker** [comment]
Well I certainly appreciate your time. Do you think there is an issue with the $_SESSION store by chance? Will the app registration redirect URI accept https?

**Comment by jasonjoh** [comment]
Not sure why $_SESSION wouldn't work on production. App registrations require HTTPS on redirect URIs. Only exception is for localhost to ease development :).
