### ISSUE TITLE
always getting Request returned HTTP error 404

### ISSUE THREAD

**Issue by oroalej** [jasonjoh/php-tutorial#2]
I always get this error "Request returned HTTP error 404" when accessing calendar.php for getting the events in calendar. i already follow the instruction in https://dev.outlook.com/RestGettingStarted/Tutorial/php

**Comment by jasonjoh** [comment]
Are you logging in with an Outlook.com account (or Hotmail.com, live.com, etc.)? It sounds like you may not have the REST APIs enabled for that account yet. There should be an error message in the body of the response with something like `MailboxNotEnabledForRESTAPI` or `MailboxNotSupportedForRESTAPI`.

**Comment by oroalej** [comment]
I think that is my problem, i know it sounds dumb but how can i enable the rest API in my account? I'm currently logged in in my outlook.com account..

**Comment by jasonjoh** [comment]
You can't enable it. We're enabling accounts in waves, and it's just random as to what wave your mailbox might be in. If you need a test account, you can get a free year of Office 365 Developer by signing up for the Office Developer Program at dev.office.com, or you can send an email to outlookdev@microsoft.com to request a developer preview Outlook.com account.

**Comment by oroalej** [comment]
oh, that's what i thought. so that's the reason why i can find any option about that outlook rest api enable in the outlook options and account settings. thank you @jasonjoh  for replying.

**Comment by mansouralex** [comment]
Hello @jasonjoh For the accounts that not yet enabled, is there any alternative that we can authorize these users accounts through our app?

Actually, what I'm interested in at the moment is the Mail API.

Thanks.

**Comment by jasonjoh** [comment]
Well you can _authorize_ via OpenID Connect, but you can't access the API until they are enabled.

**Comment by mansouralex** [comment]
Thanks for your reply. Any estimates when all accounts will get enabled?

Is there any other active services you offer to access the Mail ?

**Comment by brutuscat** [comment]
@jasonjoh I'm also interested to know more about when these "enabling waves" will be finished and all the mailboxes will be api-ready. Do you guys have an ETA? Where should we ask or subscribe for news about this?

Thank you!

**Comment by jasonjoh** [comment]
I know you guys are eager, but unfortunately I don't have an ETA. All newly created accounts are enabled at creation, but we're still working through pre-existing accounts.
