### ISSUE TITLE
 InternetMessageId and message_id from headers returns blank value in response

### ISSUE THREAD

**Issue by laurelBE** [jasonjoh/php-tutorial#26]
Hi everyone, I am using API for mail retrieving, it display mail properly but i want some additional info.
Following is my code

```
$expand='SingleValueExtendedProperties';
    $search = array (
        // Only return selected fields
        "\$select" => "Subject,ReceivedDateTime,Sender,SingleValueExtendedProperties,From,ToRecipients,HasAttachments,BodyPreview,InternetMessageHeaders,internetMessageId",
        // Sort by ReceivedDateTime, newest first
        "\$orderby" => "ReceivedDateTime DESC",
        // Return at most n results
        "\$top" => $top,

		"expand"=>$expand,
		"\$skip" => $skip
    );
    $outlookApiUrl = $_SESSION["api_url"] . "/Me/MailFolders/Inbox/Messages?" . http_build_query($search);
```
But i am getting response InternetMessageId and message_id as blank value,but in sandbox it gives proper InternetMessageId, what should it required ?
Please help me

**Comment by jasonjoh** [comment]
You've missed the capital `I` in the property name in your select statement. It should be `InternetMessageId`.

Please post questions like this on StackOverflow as they don't directly relate to this sample. You'll get better visibility there and your question can help more people :)
