### ISSUE TITLE
Cannot fetch emails from inbox

### ISSUE THREAD

**Issue by rezaffm** [jasonjoh/php-tutorial#28]
I followed the tutorial - it works until I receive an accessToken and then I show my name.

However, when I try to fetch messages, I get the following error:

GuzzleHttp\Exception\ClientException thrown with message "Client error: `GET https://graph.microsoft.com/v1.0/me/MailFolders/INBOX/messages` resulted in a `404 Not Found` response:
{
  "error": {
    "code": "ResourceNotFound",
    "message": "Resource could not be discovered.",
    "innerError": (truncated...)
"

Stacktrace:
#63 GuzzleHttp\Exception\ClientException in /var/www/html/php-tutorial/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113
#62 GuzzleHttp\Exception\RequestException:create in /var/www/html/php-tutorial/vendor/guzzlehttp/guzzle/src/Middleware.php:66
#61 GuzzleHttp\Middleware:GuzzleHttp\{closure} in /var/www/html/php-tutorial/vendor/guzzlehttp/promises/src/Promise.php:203
#60 GuzzleHttp\Promise\Promise:callHandler in /var/www/html/php-tutorial/vendor/guzzlehttp/promises/src/Promise.php:156
#59 GuzzleHttp\Promise\Promise:GuzzleHttp\Promise\{closure} in /var/www/html/php-tutorial/vendor/guzzlehttp/promises/src/TaskQueue.php:47
#58 GuzzleHttp\Promise\TaskQueue:run in /var/www/html/php-tutorial/vendor/guzzlehttp/promises/src/Promise.php:246
#57 GuzzleHttp\Promise\Promise:invokeWaitFn in /var/www/html/php-tutorial/vendor/guzzlehttp/promises/src/Promise.php:223
#56 GuzzleHttp\Promise\Promise:waitIfPending in /var/www/html/php-tutorial/vendor/guzzlehttp/promises/src/Promise.php:267
#55 GuzzleHttp\Promise\Promise:invokeWaitList in /var/www/html/php-tutorial/vendor/guzzlehttp/promises/src/Promise.php:225
#54 GuzzleHttp\Promise\Promise:waitIfPending in /var/www/html/php-tutorial/vendor/guzzlehttp/promises/src/Promise.php:62
#53 GuzzleHttp\Promise\Promise:wait in /var/www/html/php-tutorial/vendor/guzzlehttp/guzzle/src/Client.php:131
#52 GuzzleHttp\Client:request in /var/www/html/php-tutorial/vendor/microsoft/microsoft-graph/src/Http/GraphRequest.php:236
#51 Microsoft\Graph\Http\GraphRequest:execute in /var/www/html/php-tutorial/app/Http/Controllers/OutlookController.php:40
#50 App\Http\Controllers\OutlookController:mail in /var/www/html/php-tutorial/vendor/laravel/framework/src/Illuminate/Routing/Controller.php:54
#49 call_user_func_array in /var/www/html/php-tutorial/vendor/laravel/framework/src/Illuminate/Routing/Controller.php:54
#48 Illuminate\Routing\Controller:callAction in /var/www/html/php-tutorial/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php:45
#47 Illuminate\Routing\ControllerDispatcher:dispatch in /var/www/html/php-tutorial/vendor/laravel/framework/src/Illuminate/Routing/Route.php:212
#46 Illuminate\Routing\Route:runController in /var/www/html/php-tutorial/vendor/laravel/framework/src/Illuminate/Routing/Route.php:169
#45 Illuminate\Routing\Route:run in /var/www/html/php-tutorial/vendor/laravel/framework/src/Illuminate/Routing/Router.php:679
#44 Illuminate\Routing\Router:Illuminate\Routing\{closure} in /var/www/html/php-tutorial/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:30
#43 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/html/php-tutorial/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php:41
#42 Illuminate\Routing\Middleware\SubstituteBindings:handle in /var/www/html/php-tutorial/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
#41 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/html/php-tutorial/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#40 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/html/php-tutorial/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php:75
#39 Illuminate\Foundation\Http\Middleware\VerifyCsrfToken:handle in /var/www/html/php-tutorial/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
#38 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/html/php-tutorial/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#37 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/html/php-tutorial/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php:49
#36 Illuminate\View\Middleware\ShareErrorsFromSession:handle in /var/www/html/php-tutorial/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
#35 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/html/php-tutorial/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#34 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/html/php-tutorial/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php:63
#33 Illuminate\Session\Middleware\StartSession:handle in /var/www/html/php-tutorial/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
#32 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/html/php-tutorial/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#31 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/html/php-tutorial/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php:37
#30 Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse:handle in /var/www/html/php-tutorial/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
#29 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/html/php-tutorial/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#28 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/html/php-tutorial/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php:66
#27 Illuminate\Cookie\Middleware\EncryptCookies:handle in /var/www/html/php-tutorial/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
#26 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/html/php-tutorial/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#25 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/html/php-tutorial/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:104
#24 Illuminate\Pipeline\Pipeline:then in /var/www/html/php-tutorial/vendor/laravel/framework/src/Illuminate/Routing/Router.php:681
#23 Illuminate\Routing\Router:runRouteWithinStack in /var/www/html/php-tutorial/vendor/laravel/framework/src/Illuminate/Routing/Router.php:656
#22 Illuminate\Routing\Router:runRoute in /var/www/html/php-tutorial/vendor/laravel/framework/src/Illuminate/Routing/Router.php:622
#21 Illuminate\Routing\Router:dispatchToRoute in /var/www/html/php-tutorial/vendor/laravel/framework/src/Illuminate/Routing/Router.php:611
#20 Illuminate\Routing\Router:dispatch in /var/www/html/php-tutorial/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:176
#19 Illuminate\Foundation\Http\Kernel:Illuminate\Foundation\Http\{closure} in /var/www/html/php-tutorial/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:30
#18 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/html/php-tutorial/vendor/fideloper/proxy/src/TrustProxies.php:57
#17 Fideloper\Proxy\TrustProxies:handle in /var/www/html/php-tutorial/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
#16 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/html/php-tutorial/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#15 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/html/php-tutorial/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php:31
#14 Illuminate\Foundation\Http\Middleware\TransformsRequest:handle in /var/www/html/php-tutorial/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
#13 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/html/php-tutorial/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#12 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/html/php-tutorial/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php:31
#11 Illuminate\Foundation\Http\Middleware\TransformsRequest:handle in /var/www/html/php-tutorial/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
#10 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/html/php-tutorial/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#9 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/html/php-tutorial/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php:27
#8 Illuminate\Foundation\Http\Middleware\ValidatePostSize:handle in /var/www/html/php-tutorial/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
#7 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/html/php-tutorial/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#6 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/html/php-tutorial/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php:62
#5 Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode:handle in /var/www/html/php-tutorial/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
#4 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/html/php-tutorial/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#3 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/html/php-tutorial/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:104
#2 Illuminate\Pipeline\Pipeline:then in /var/www/html/php-tutorial/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:151
#1 Illuminate\Foundation\Http\Kernel:sendRequestThroughRouter in /var/www/html/php-tutorial/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:116
#0 Illuminate\Foundation\Http\Kernel:handle in /var/www/html/php-tutorial/public/index.php:55

I dont understand this. I used Oauth before, also in Laravel projects. What am I missing? 
Thank you!

**Comment by jasonjoh** [comment]
Most likely you do not have an Office 365/Outlook.com mailbox associated with the account you used to login.

**Comment by rezaffm** [comment]
Well, I found out that pur Server is outdated (2013) so that is the Tessin.
