### ISSUE TITLE
I am facing a access token issue

### ISSUE THREAD

**Issue by anujaunds** [jasonjoh/php-tutorial#29]
I have account on microsoft dynamic 365 and i install your api module with my laravel website as per your document, but still i am facing the one error "No access token has been provided".  i was uploaded cacert.pem file on server, but still showing a same error. Could you please help me, how i resolved this issue.[](url)
<img width="1998" alt="screenshot 2018-11-26 at 16 35 46" src="https://user-images.githubusercontent.com/38660798/49024663-4e8e3400-f19a-11e8-825f-083533c4ded6.png">

**Comment by jasonjoh** [comment]
You provide the access token to the Graph client by calling `setAccessToken` (see https://github.com/jasonjoh/php-tutorial/blob/08a7293d1eb4577819f305c5b089b4f55f4afd47/app/Http/Controllers/OutlookController.php#L90)

That's where you should start debugging this. You either don't have a token in the cache for some reason or you're missing this line.

**Comment by anujaunds** [comment]
Hi,
This line is there but i don't know why this can't take access token. could you please let me this laravel module i used to get contacts from microsoft CRM. 

Regards,
Anuj Sharma

**Comment by jasonjoh** [comment]
I'm happy to help you but I really don't have enough information to begin to help. You'll need to debug this on your side to find out what's going wrong. Start by debugging what happens in the AuthController.php functions. `gettoken` might be failing, or it could be that it works but the token isn't getting stored in the session correctly.
