### ISSUE TITLE
Authentication failed and AuthCode not returned.

### ISSUE THREAD

**Issue by Capall** [jasonjoh/php-tutorial#3]
Hi ! I'm following the tutorial and I'm stuck just after the creation of authorize.php.
I can enter my email and my password on the identification page but when I'm redirected on my site, it just show "Auth code : " without the code.

In the URL I can see this : 

Error : Unauthorized client
Error description : Application is not supported for this API version.

I don't understand what does it mean. I logged in with the same adress that I used to create my app.
Can someone help me please ?

**Comment by jasonjoh** [comment]
Sorry you're having trouble! Are you by chance logging in with an Outlook.com account (Hotmail.com, Live.com, etc?) If so my suspicion is that the account isn't enabled for the REST APIs yet.

**Comment by Capall** [comment]
Thanks for your answer :)
Yes I used my personnal account. I deduce I will need to create a developer account ?
Is it easy to have ?

**Comment by jasonjoh** [comment]
It would be good to verify that's the problem. Can you go to https://oauthplay.azurewebsites.net/ and try logging in and running the default query? What's the response?

**Comment by Capall** [comment]
Here's the response : POST https://outlook.office.com/api/v2.0/me/mailfolders/inbox/messages?$top=10 HTTP/1.1

**Comment by Capall** [comment]
I don't know what is the response you want so I give you both : 
GET https://outlook.office.com/api/v2.0/me/mailfolders/inbox/messages?$top=10 HTTP/1.1
Accept: text/*, application/xml, application/json; odata.metadata=none

User-Agent: PlayGroundAgent/1.0

Authorization: Bearer EwCAAul3BAAUo4xeBIbHjhBxWOFekj4Xy2fhaGQAAV2MO92ckmw2DILJKoEgD5s32CgscKNq3JtYTMuPTvUVtl3cdydablk0sQDIQHiGOQXRKCn6FwfQWiK23e5PWMFDySD2dHKJbeqaK8X313oIn0KWA5FELjvdSUXX39tqcZWS+JNsMq3RK7UNv4k1BCoUuNeRuhUYb4OSNtVhZHQY2O41tyEuyG/I9+l74fzvE/nJk/nI1miHF9GsXU0ztk3ytqzPn9+/kgpJ8k5910SC+8VGH0JqHoTHO/yuhOIew1kMBObDWMixeiS1wl6e9AfHU7V1FXoey5kyj13sfk9+/0jFY9+CkLx7OyOb7IUz8FESlvXTaKJE39u4Z4Jl/5ADZgAACDWfvCL7+d7aUAFxdIvIFFVV3wAFuY2Wd2XN7WAQmoC+HMfU/c///GSJ8HMA6zHQ+AUISuC9TBaxz1vkMI8VS4Hflq+XD2TNGDmu8plwC5cafIBKrbff5sIzOeH30PbeoUN1JqSczOn9MhhAZiD5PJ6ENcOc0iqIs6NCo9ZBK+klqSx/Bdl4F+1wFrgjkZHe8kouu3VLxYPBmfdjZQ9ojHXDIuKkn60KSmAECd2sQB24bsVjyWVUnSL3059feEeXr/AA8872S+3m0RpNbo7C7nX5efRnZgpcBmaGrEHnuP8EYZCuYeY3HYnJ9AxQzuApVeAr75yerKambkJZ9LZffvJHNxLInpldR4sIT0WVI44bcQFwvLkwpw/ap801N38zE4USGaz9gaIR86Op+lBVDID+ZdC61e+sXO9IKv2Z1F7j3OQn33S2qtgYCkrph/ZL7UZlVWnUGn4M+SdlAQ==

client-request-id: 508bbcde-8ec0-45d0-b0fc-a0826bc7ac8d

X-AnchorMailbox: capall@outlook.com

And the second :

HTTP/1.1 400 Bad Request
Transfer-Encoding: chunked

Cache-Control: private

Set-Cookie: ClientId=SJKL6UMM9EAPOTYXKATHQ; expires=Thu, 15-Dec-2016 07:15:11 GMT; path=/; secure; HttpOnly, exchangecookie=a3ee761c57a847ac922c5cceb693cd4a; expires=Fri, 16-Dec-2016 07:15:12 GMT; path=/; HttpOnly, X-BackEndCookie2=actas1(netid:00037FFEBC22FCDB)=rJqNiZqNgb2mza+tz82yvc3Jx9GRnpKPjZvPzdGPjZCb0ZCKi5OQkJTRnJCSgc7Gy83Pyc7Mx8iBzc/OytLOzdLOyavPyMXNysXOyw==; expires=Wed, 16-Dec-2015 07:25:14 GMT; path=/api; secure; HttpOnly, X-BackEndCookie=actas1(netid:00037FFEBC22FCDB)=rJqNiZqNgb2mza+tz82yvc3Jx9GRnpKPjZvPzdGPjZCb0ZCKi5OQkJTRnJCSgc7Gy83Pyc7Mx8iBzc/OytLOzdLOyavPyMXNysXOyw==; expires=Wed, 16-Dec-2015 07:25:14 GMT; path=/api; secure; HttpOnly

Server: Microsoft-IIS/8.5

request-id: ec6111a3-27d7-4470-a3f0-c5041b66ef1f

X-CalculatedBETarget: by2pr02mb268.namprd02.prod.outlook.com

OData-Version: 4.0

X-DiagInfo: BY2PR02MB268

X-BEServer: BY2PR02MB268

X-AspNet-Version: 4.0.30319

X-Powered-By: ASP.NET

X-MSEdge-Ref: Ref A: 5398877C48E44CB0B4FDAD605CFED63C Ref B: 3DD80A8B6B528A8F858DAB76C1EF8C4F Ref C: Tue Dec 15 23:15:14 2015 PST

Date: Wed, 16 Dec 2015 07:15:13 GMT

{
    "error": {
        "code": "ErrorMissingEmailAddress",
        "message": "When making a request as an account that does not have a mailbox, you must specify the mailbox primary SMTP address for any distinguished folder Ids."
    }
}

**Comment by jasonjoh** [comment]
Ok thank you. That confirms that your mailbox hasn't been enabled for the REST API. Eventually all outlook.com accounts will be enabled, but we're enabling them in batches, and it's just a matter of waiting until your account gets enabled.

In the meantime, your best bet to get up and running quickly would be to join the Office Developer Program and get a free Office 365 Developer subscription: http://dev.office.com/devprogram. You can use that to test your code.
