### ISSUE TITLE
Error while loading

### ISSUE THREAD

**Issue by larsbrandi** [jasonjoh/php-tutorial#4]
Hi I have tried the code out. It is a newly created outlook account, and Application Id and secrets has been applied. The code halts in line 35 in home.php and I made a var_dump of $messages. The result where "array(2) { ["errorNumber"]=> int(400) ["error"]=> string(31) "Request returned HTTP error 400" }". So I went to https://oauthplay.azurewebsites.net/ to checkout what was going on, and got this result : 

HTTP/1.1 400 Bad Request
Transfer-Encoding: chunked

Cache-Control: private

Set-Cookie: ClientId=1NZ8GTCJ40ODODMXLPZQW; expires=Wed, 14-Dec-2016 21:26:53 GMT; path=/; secure; HttpOnly, exchangecookie=63f0f8dcbe5b4deb8315b93683323486; expires=Thu, 15-Dec-2016 21:26:55 GMT; path=/; HttpOnly, X-BackEndCookie2=actas1(netid:00034001D3166E57)=rJqNiZqNgb2mzq+tz8nPzrK9zs/JzNGRnpKPjZvPydGPjZCb0ZCKi5OQkJTRnJCSgc7Gy83Pyc7Lzs6Bzc/OytLOzdLOyqvNzsXMycXKyA==; expires=Tue, 15-Dec-2015 21:36:57 GMT; path=/api; secure; HttpOnly, X-BackEndCookie=actas1(netid:00034001D3166E57)=rJqNiZqNgb2mzq+tz8nPzrK9zs/JzNGRnpKPjZvPydGPjZCb0ZCKi5OQkJTRnJCSgc7Gy83Pyc7Lzs6Bzc/OytLOzdLOyqvNzsXMycXKyA==; expires=Tue, 15-Dec-2015 21:36:57 GMT; path=/api; secure; HttpOnly

Server: Microsoft-IIS/8.5

request-id: 1aa68186-a587-45cc-a21e-c0e5d28ba0ca

X-CalculatedBETarget: by1pr0601mb1063.namprd06.prod.outlook.com

OData-Version: 4.0

X-DiagInfo: BY1PR0601MB1063

X-BEServer: BY1PR0601MB1063

X-AspNet-Version: 4.0.30319

X-Powered-By: ASP.NET

X-MSEdge-Ref: Ref A: 18D0F129E7FE4FF2AE05D61717ED9D3E Ref B: 57D3F5F1111FC304AFF33A4C31140305 Ref C: Tue Dec 15 13:26:57 2015 PST

Date: Tue, 15 Dec 2015 21:26:56 GMT

{
    "error": {
        "code": "ErrorMissingEmailAddress",
        "message": "When making a request as an account that does not have a mailbox, you must specify the mailbox primary SMTP address for any distinguished folder Ids."
    }
}

Any clue on what is going on ?

**Comment by larsbrandi** [comment]
I tried with a friends office 365. It works, so it is obviously my account.

**Comment by jasonjoh** [comment]
Yes, this is the same issue as #3. Your outlook.com account isn't enabled for the REST APIs. See #3 for details.
