### ISSUE TITLE
mail send using php code getting  "Request returned HTTP error 400"

### ISSUE THREAD

**Issue by anantapl** [jasonjoh/php-tutorial#5]
public static function sendMessages($access_token, $user_email) {
      $getMessagesParameters = array(
            '\$Message'=>array(
            '\$Subject' => "Hello this is a test mail subject.",
            '\$Body' => array('\$ContentType'=>"Text",'\$Content'=>"This is a test content"),
            '\$ToRecipients' => array('\$EmailAddress'=>array('\$Address'=>"receiveremail@xyz.com")),  
            '\$SaveToSentItems' => "false"  
            )
        );  
      $getMessagesUrl = self::$outlookApiUrl."/me/sendmail?".http_build_query($getMessagesParameters);  
      return self::makeApiCall($access_token, $user_email, "POST", $getMessagesUrl);
}

**Comment by jasonjoh** [comment]
Yep, that's not sending the proper format. You're adding the message parameters to the query, which will put it in the request URL. When sending mail, the message parameters need to go as JSON in the body of the request. You need to pass that in the `$payload` parameter to `makeApiCall`.

**Comment by anantapl** [comment]
Can you please make the code ?
